#pprint of eventResult from quickstart.py

#user info
{u'accessRole': u'owner',
 u'defaultReminders': [{u'method': u'popup', u'minutes': 10}],
 u'etag': u'"1462750409499000"',
 u'items': [

            #first event
            {u'created': u'2016-05-05T05:48:38.000Z',
             u'creator': {u'email': u'megan@lunchdragon.com', u'self': True},
             u'end': {u'date': u'2016-05-10'},
             u'etag': u'"2924854759356000"',
             u'hangoutLink': u'https://plus.google.com/hangouts/_/lunchdragon.com/megan?hceid=bWVnYW5AbHVuY2hkcmFnb24uY29t.sapfclg7jg6u41srgojjt66vdo',
             u'htmlLink': u'https://www.google.com/calendar/event?eid=c2FwZmNsZzdqZzZ1NDFzcmdvamp0NjZ2ZG9fMjAxNjA1MDkgbWVnYW5AbHVuY2hkcmFnb24uY29t',
             u'iCalUID': u'sapfclg7jg6u41srgojjt66vdo@google.com',
             u'id': u'sapfclg7jg6u41srgojjt66vdo_20160509',
             u'kind': u'calendar#event',
             u'organizer': {u'email': u'megan@lunchdragon.com',
                            u'self': True},
             u'originalStartTime': {u'date': u'2016-05-09'},
             u'recurringEventId': u'sapfclg7jg6u41srgojjt66vdo',
             u'reminders': {u'useDefault': False},
             u'sequence': 1,
             u'start': {u'date': u'2016-05-09'},
             u'status': u'confirmed',
             u'summary': u'WFH',
             u'updated': u'2016-05-05T05:49:39.722Z'},

             #attendees for second event
            {u'attendees': [{u'displayName': u'conf-rm-2',
                             u'email': u'lunchdragon.com_2d36383735373836312d373238@resource.calendar.google.com',
                             u'resource': True,
                             u'responseStatus': u'accepted'},
                            {u'email': u'megan@lunchdragon.com',
                             u'organizer': True,
                             u'responseStatus': u'accepted',
                             u'self': True},
                            {u'email': u'don@lunchdragon.com',
                             u'responseStatus': u'needsAction'}],

                            [{u'resource': True,
                                u'displayName': u'conf-rm-2',
                                u'email': u'lunchdragon.com_2d36383735373836312d373238@resource.calendar.google.com',
                                u'responseStatus': u'accepted'},
                            {u'responseStatus': u'accepted',
                                u'organizer': True,
                                u'email': u'megan@lunchdragon.com',
                                u'self': True},
                            {u'email': u'don@lunchdragon.com',
                                u'responseStatus': u'needsAction'}]

                 #second event
                 u'created': u'2016-05-08T21:26:44.000Z',
                 u'creator': {u'email': u'megan@lunchdragon.com', u'self': True},
                 u'end': {u'dateTime': u'2016-05-11T13:00:00-07:00'},
                 u'etag': u'"2925485633198000"',
                 u'hangoutLink': u'https://plus.google.com/hangouts/_/lunchdragon.com/megan?hceid=bWVnYW5AbHVuY2hkcmFnb24uY29t.39cie0a6ll2342fgm9paepmqfg',
                 u'htmlLink': u'https://www.google.com/calendar/event?eid=MzljaWUwYTZsbDIzNDJmZ205cGFlcG1xZmcgbWVnYW5AbHVuY2hkcmFnb24uY29t',
                 u'iCalUID': u'39cie0a6ll2342fgm9paepmqfg@google.com',
                 u'id': u'39cie0a6ll2342fgm9paepmqfg',
                 u'kind': u'calendar#event',
                 u'location': u'conf-rm-2',
                 u'organizer': {u'email': u'megan@lunchdragon.com',
                                u'self': True},
                 u'reminders': {u'useDefault': True},
                 u'sequence': 0,
                 u'start': {u'dateTime': u'2016-05-11T12:00:00-07:00'},
                 u'status': u'confirmed',
                 u'summary': u'Standup',
                 u'updated': u'2016-05-08T21:26:56.599Z'},

             #third event
            {u'created': u'2016-05-05T05:48:38.000Z',
             u'creator': {u'email': u'megan@lunchdragon.com', u'self': True},
             u'end': {u'date': u'2016-05-17'},
             u'etag': u'"2924854759356000"',
             u'hangoutLink': u'https://plus.google.com/hangouts/_/lunchdragon.com/megan?hceid=bWVnYW5AbHVuY2hkcmFnb24uY29t.sapfclg7jg6u41srgojjt66vdo',
             u'htmlLink': u'https://www.google.com/calendar/event?eid=c2FwZmNsZzdqZzZ1NDFzcmdvamp0NjZ2ZG9fMjAxNjA1MTYgbWVnYW5AbHVuY2hkcmFnb24uY29t',
             u'iCalUID': u'sapfclg7jg6u41srgojjt66vdo@google.com',
             u'id': u'sapfclg7jg6u41srgojjt66vdo_20160516',
             u'kind': u'calendar#event',
             u'organizer': {u'email': u'megan@lunchdragon.com',
                            u'self': True},
             u'originalStartTime': {u'date': u'2016-05-16'},
             u'recurringEventId': u'sapfclg7jg6u41srgojjt66vdo',
             u'reminders': {u'useDefault': False},
             u'sequence': 1,
             u'start': {u'date': u'2016-05-16'},
             u'status': u'confirmed',
             u'summary': u'WFH',
             u'updated': u'2016-05-05T05:49:39.722Z'},

             #4th event
            {u'created': u'2016-05-05T05:48:38.000Z',
             u'creator': {u'email': u'megan@lunchdragon.com', u'self': True},
             u'end': {u'date': u'2016-05-24'},
             u'etag': u'"2924854759356000"',
             u'hangoutLink': u'https://plus.google.com/hangouts/_/lunchdragon.com/megan?hceid=bWVnYW5AbHVuY2hkcmFnb24uY29t.sapfclg7jg6u41srgojjt66vdo',
             u'htmlLink': u'https://www.google.com/calendar/event?eid=c2FwZmNsZzdqZzZ1NDFzcmdvamp0NjZ2ZG9fMjAxNjA1MjMgbWVnYW5AbHVuY2hkcmFnb24uY29t',
             u'iCalUID': u'sapfclg7jg6u41srgojjt66vdo@google.com',
             u'id': u'sapfclg7jg6u41srgojjt66vdo_20160523',
             u'kind': u'calendar#event',
             u'organizer': {u'email': u'megan@lunchdragon.com',
                            u'self': True},
             u'originalStartTime': {u'date': u'2016-05-23'},
             u'recurringEventId': u'sapfclg7jg6u41srgojjt66vdo',
             u'reminders': {u'useDefault': False},
             u'sequence': 1,
             u'start': {u'date': u'2016-05-23'},
             u'status': u'confirmed',
             u'summary': u'WFH',
             u'updated': u'2016-05-05T05:49:39.722Z'},

             #fifth event
            {u'created': u'2016-05-05T05:48:38.000Z',
             u'creator': {u'email': u'megan@lunchdragon.com', u'self': True},
             u'end': {u'date': u'2016-05-31'},
             u'etag': u'"2924854759356000"',
             u'hangoutLink': u'https://plus.google.com/hangouts/_/lunchdragon.com/megan?hceid=bWVnYW5AbHVuY2hkcmFnb24uY29t.sapfclg7jg6u41srgojjt66vdo',
             u'htmlLink': u'https://www.google.com/calendar/event?eid=c2FwZmNsZzdqZzZ1NDFzcmdvamp0NjZ2ZG9fMjAxNjA1MzAgbWVnYW5AbHVuY2hkcmFnb24uY29t',
             u'iCalUID': u'sapfclg7jg6u41srgojjt66vdo@google.com',
             u'id': u'sapfclg7jg6u41srgojjt66vdo_20160530',
             u'kind': u'calendar#event',
             u'organizer': {u'email': u'megan@lunchdragon.com',
                            u'self': True},
             u'originalStartTime': {u'date': u'2016-05-30'},
             u'recurringEventId': u'sapfclg7jg6u41srgojjt66vdo',
             u'reminders': {u'useDefault': False},
             u'sequence': 1,
             u'start': {u'date': u'2016-05-30'},
             u'status': u'confirmed',
             u'summary': u'WFH',
             u'updated': u'2016-05-05T05:49:39.722Z'}],

#user info
 u'kind': u'calendar#events',
 u'summary': u'megan@lunchdragon.com',
 u'timeZone': u'America/Los_Angeles',
 u'updated': u'2016-05-08T23:33:29.499Z'}
